=== Java1Guy/ivolunteer/server/src/xml/voml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.networkforgood.org/xml/namespaces/voml/" xmlns:voml="http://www.networkforgood.org/xml/namespaces/voml/">
  <xs:import schemaLocation="local.xsd"/>
  <xs:element name="VolunteerOpportunities">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="voml:VolunteerOpportunity"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VolunteerOpportunity">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:LocalID"/>
        <xs:element minOccurs="0" ref="voml:Categories"/>
        <xs:element minOccurs="0" ref="voml:DateListed"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="voml:Title"/>
          <xs:element ref="voml:DetailURL"/>
          <xs:element ref="voml:LogoURL"/>
          <xs:element ref="voml:Description"/>
          <xs:element ref="voml:Locations"/>
        </xs:sequence>
        <xs:element minOccurs="0" ref="voml:SpecialInstructions"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="voml:OpportunityDates"/>
          <xs:element ref="voml:Audiences"/>
          <xs:element ref="voml:LocationClassifications"/>
          <xs:element ref="voml:OpportunityType"/>
        </xs:sequence>
        <xs:element minOccurs="0" ref="voml:Comments"/>
        <xs:element minOccurs="0" ref="voml:SponsoringOrganizations"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LocalID" type="xs:integer"/>
  <xs:element name="Categories">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="voml:Category"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Category">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:CategoryID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CategoryID" type="xs:integer"/>
  <xs:element name="DateListed" type="xs:NMTOKEN"/>
  <xs:element name="Title" type="xs:string"/>
  <xs:element name="DetailURL" type="xs:anyURI"/>
  <xs:element name="Description">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="voml:EMAIL"/>
        <xs:element ref="voml:FAX"/>
        <xs:element ref="voml:a"/>
        <xs:element ref="voml:b"/>
        <xs:element ref="voml:br"/>
        <xs:element ref="voml:strong"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="EMAIL">
    <xs:complexType/>
  </xs:element>
  <xs:element name="FAX">
    <xs:complexType/>
  </xs:element>
  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:attribute name="href" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType/>
  </xs:element>
  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  <xs:element name="strong" type="xs:string"/>
  <xs:element name="Locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:Location"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Location">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="voml:Address1"/>
        <xs:element minOccurs="0" ref="voml:Address2"/>
        <xs:element minOccurs="0" ref="voml:City"/>
        <xs:element minOccurs="0" ref="voml:StateOrProvince"/>
        <xs:element minOccurs="0" ref="voml:ZipOrPostalCode"/>
        <xs:element minOccurs="0" ref="voml:Country"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SpecialInstructions" type="xs:string"/>
  <xs:element name="OpportunityDates">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:OpportunityDate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OpportunityDate">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="voml:StartDate"/>
        <xs:element minOccurs="0" ref="voml:EndDate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StartDate" type="xs:NMTOKEN"/>
  <xs:element name="EndDate" type="xs:NMTOKEN"/>
  <xs:element name="Audiences">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="voml:Audience"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Audience">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:AudienceID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AudienceID" type="xs:integer"/>
  <xs:element name="LocationClassifications">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:LocationClassification"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LocationClassification">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:LocationClassificationID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LocationClassificationID" type="xs:integer"/>
  <xs:element name="OpportunityType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:OpportunityTypeID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OpportunityTypeID" type="xs:integer"/>
  <xs:element name="Comments" type="xs:string"/>
  <xs:element name="SponsoringOrganizations">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="voml:SponsoringOrganization"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SponsoringOrganization">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voml:Name"/>
        <xs:element minOccurs="0" ref="voml:Address1"/>
        <xs:element minOccurs="0" ref="voml:Address2"/>
        <xs:element minOccurs="0" ref="voml:City"/>
        <xs:element minOccurs="0" ref="voml:StateOrProvince"/>
        <xs:element minOccurs="0" ref="voml:ZipOrPostalCode"/>
        <xs:element minOccurs="0" ref="voml:Country"/>
        <xs:element minOccurs="0" ref="voml:Phone"/>
        <xs:element minOccurs="0" ref="voml:Extension"/>
        <xs:element minOccurs="0" ref="voml:Fax"/>
        <xs:element minOccurs="0" ref="voml:Email"/>
        <xs:element minOccurs="0" ref="voml:URL"/>
        <xs:element minOccurs="0" ref="voml:LogoURL"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:string"/>
  <xs:element name="Phone" type="xs:string"/>
  <xs:element name="Extension" type="xs:string"/>
  <xs:element name="Fax" type="xs:string"/>
  <xs:element name="Email" type="xs:anyURI"/>
  <xs:element name="URL" type="xs:string"/>
  <xs:element name="LogoURL" type="xs:anyURI"/>
  <xs:element name="Address1" type="xs:string"/>
  <xs:element name="Address2" type="xs:string"/>
  <xs:element name="City" type="xs:string"/>
  <xs:element name="StateOrProvince" type="xs:NCName"/>
  <xs:element name="ZipOrPostalCode" type="xs:string"/>
  <xs:element name="Country" type="xs:string"/>
</xs:schema>

=== Java1Guy/ivolunteer/server/server-ejb/src/xml-resources/jaxb/voml/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:VolunteerOpportunities xmlns:ns1="http://www.networkforgood.org/xml/namespaces/voml/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.networkforgood.org/xml/namespaces/voml/ file:/Users/dave/Documents/iVolunteer/code/ivolunteer/server/server-ejb/src/conf/xml-resources/jaxb/voml/voml.xsd">
    <ns1:VolunteerOpportunity>
        <ns1:LocalID>LocalID0</ns1:LocalID>
        <ns1:Categories>
        </ns1:Categories>
        <ns1:OpportunityType>
            <ns1:OpportunityTypeID>0</ns1:OpportunityTypeID>
        </ns1:OpportunityType>
        <ns1:Title>Title0</ns1:Title>
        <ns1:DetailURL>http://www.oxygenxml.com/</ns1:DetailURL>
        <ns1:Abstract>Abstract0</ns1:Abstract>
        <ns1:Description>Description0</ns1:Description>
        <ns1:LogoURL>http://www.oxygenxml.com/</ns1:LogoURL>
        <ns1:LocationClassifications>
            <ns1:LocationClassification>
                <ns1:LocationClassificationID>0</ns1:LocationClassificationID>
            </ns1:LocationClassification>
        </ns1:LocationClassifications>
        <ns1:Locations>
            <ns1:Location>
                <ns1:City>City0</ns1:City>
                <ns1:StateOrProvince>StateOrProvince0</ns1:StateOrProvince>
                <ns1:ZipOrPostalCode>ZipOrPostalCode0</ns1:ZipOrPostalCode>
                <ns1:Country>Country0</ns1:Country>
            </ns1:Location>
        </ns1:Locations>
        <ns1:OpportunityDates>
            <ns1:OpportunityDate>
                <ns1:StartDate>StartDate0</ns1:StartDate>
            </ns1:OpportunityDate>
            <ns1:OpportunityDate>
                <ns1:StartDate>StartDate1</ns1:StartDate>
            </ns1:OpportunityDate>
        </ns1:OpportunityDates>
        <ns1:SponsoringOrganizations>
            <ns1:SponsoringOrganization>
                <ns1:Name>Name0</ns1:Name>
            </ns1:SponsoringOrganization>
            <ns1:SponsoringOrganization>
                <ns1:Name>Name1</ns1:Name>
            </ns1:SponsoringOrganization>
        </ns1:SponsoringOrganizations>
        <ns1:LocalHubs>
        </ns1:LocalHubs>
    </ns1:VolunteerOpportunity>
    <ns1:VolunteerOpportunity>
        <ns1:LocalID>LocalID1</ns1:LocalID>
        <ns1:Categories>
        </ns1:Categories>
        <ns1:OpportunityType>
            <ns1:OpportunityTypeID>0</ns1:OpportunityTypeID>
        </ns1:OpportunityType>
        <ns1:Title>Title1</ns1:Title>
        <ns1:DetailURL>http://www.oxygenxml.com/</ns1:DetailURL>
        <ns1:Abstract>Abstract1</ns1:Abstract>
        <ns1:Description>Description1</ns1:Description>
        <ns1:LogoURL>http://www.oxygenxml.com/</ns1:LogoURL>
        <ns1:LocationClassifications>
            <ns1:LocationClassification>
                <ns1:LocationClassificationID>0</ns1:LocationClassificationID>
            </ns1:LocationClassification>
        </ns1:LocationClassifications>
        <ns1:Locations>
            <ns1:Location>
                <ns1:City>City1</ns1:City>
                <ns1:StateOrProvince>StateOrProvince1</ns1:StateOrProvince>
                <ns1:ZipOrPostalCode>ZipOrPostalCode1</ns1:ZipOrPostalCode>
                <ns1:Country>Country1</ns1:Country>
            </ns1:Location>
        </ns1:Locations>
        <ns1:OpportunityDates>
            <ns1:OpportunityDate>
                <ns1:StartDate>StartDate2</ns1:StartDate>
            </ns1:OpportunityDate>
            <ns1:OpportunityDate>
                <ns1:StartDate>StartDate3</ns1:StartDate>
            </ns1:OpportunityDate>
        </ns1:OpportunityDates>
        <ns1:SponsoringOrganizations>
            <ns1:SponsoringOrganization>
                <ns1:Name>Name2</ns1:Name>
            </ns1:SponsoringOrganization>
            <ns1:SponsoringOrganization>
                <ns1:Name>Name3</ns1:Name>
            </ns1:SponsoringOrganization>
        </ns1:SponsoringOrganizations>
        <ns1:LocalHubs>
        </ns1:LocalHubs>
    </ns1:VolunteerOpportunity>
</ns1:VolunteerOpportunities>
